### ISSUE TITLE
Cannot import OrderPayment

### ISSUE THREAD

**Issue by thegcat** [pc-coholic/pretix-cashpayment#8] opened 2018-09-07 09:59 UTC
On current Pretix (1.17.1) and Plugin (2.0) versions, we see the following error:

```
Sep 07 09:47:44 pretix gunicorn[4340]: ERROR 2018-09-07 11:47:44,309 django.request exception Internal Server Error: /control/event/foo/bar/orders/
Sep 07 09:47:44 pretix gunicorn[4340]: Traceback (most recent call last):
Sep 07 09:47:44 pretix gunicorn[4340]:   File "/var/pretix/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
Sep 07 09:47:44 pretix gunicorn[4340]:     response = get_response(request)
Sep 07 09:47:44 pretix gunicorn[4340]:   File "/var/pretix/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
Sep 07 09:47:44 pretix gunicorn[4340]:     response = self.process_exception_by_middleware(e, request)
Sep 07 09:47:44 pretix gunicorn[4340]:   File "/var/pretix/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
Sep 07 09:47:44 pretix gunicorn[4340]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
Sep 07 09:47:44 pretix gunicorn[4340]:   File "/var/pretix/venv/lib/python3.6/site-packages/pretix/control/permissions.py", line 27, in wrapper
Sep 07 09:47:44 pretix gunicorn[4340]:     return function(request, *args, **kw)
Sep 07 09:47:44 pretix gunicorn[4340]:   File "/var/pretix/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
Sep 07 09:47:44 pretix gunicorn[4340]:     return self.dispatch(request, *args, **kwargs)
Sep 07 09:47:44 pretix gunicorn[4340]:   File "/var/pretix/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
Sep 07 09:47:44 pretix gunicorn[4340]:     return handler(request, *args, **kwargs)
Sep 07 09:47:44 pretix gunicorn[4340]:   File "/var/pretix/venv/lib/python3.6/site-packages/django/views/generic/list.py", line 160, in get
Sep 07 09:47:44 pretix gunicorn[4340]:     self.object_list = self.get_queryset()
Sep 07 09:47:44 pretix gunicorn[4340]:   File "/var/pretix/venv/lib/python3.6/site-packages/pretix/control/views/orders.py", line 74, in get_queryset
Sep 07 09:47:44 pretix gunicorn[4340]:     if self.filter_form.is_valid():
Sep 07 09:47:44 pretix gunicorn[4340]:   File "/var/pretix/venv/lib/python3.6/site-packages/django/utils/functional.py", line 35, in __get__
Sep 07 09:47:44 pretix gunicorn[4340]:     res = instance.__dict__[self.name] = self.func(instance)
Sep 07 09:47:44 pretix gunicorn[4340]:   File "/var/pretix/venv/lib/python3.6/site-packages/pretix/control/views/orders.py", line 86, in filter_form
Sep 07 09:47:44 pretix gunicorn[4340]:     return EventOrderFilterForm(data=self.request.GET, event=self.request.event)
Sep 07 09:47:44 pretix gunicorn[4340]:   File "/var/pretix/venv/lib/python3.6/site-packages/pretix/control/forms/filter.py", line 197, in __init__
Sep 07 09:47:44 pretix gunicorn[4340]:     in self.event.get_payment_providers().items()]
Sep 07 09:47:44 pretix gunicorn[4340]:   File "/var/pretix/venv/lib/python3.6/site-packages/pretix/base/models/event.py", line 470, in get_payment_providers
Sep 07 09:47:44 pretix gunicorn[4340]:     responses = register_payment_providers.send(self)
Sep 07 09:47:44 pretix gunicorn[4340]:   File "/var/pretix/venv/lib/python3.6/site-packages/pretix/base/signals.py", line 69, in send
Sep 07 09:47:44 pretix gunicorn[4340]:     response = receiver(signal=self, sender=sender, **named)
Sep 07 09:47:44 pretix gunicorn[4340]:   File "/var/pretix/venv/lib/python3.6/site-packages/pretix_cashpayment/signals.py", line 9, in register_payment_provider
Sep 07 09:47:44 pretix gunicorn[4340]:     from .payment import CashPayment
Sep 07 09:47:44 pretix gunicorn[4340]:   File "/var/pretix/venv/lib/python3.6/site-packages/pretix_cashpayment/payment.py", line 9, in <module>
Sep 07 09:47:44 pretix gunicorn[4340]:     from pretix.base.models import OrderPayment
Sep 07 09:47:44 pretix gunicorn[4340]: ImportError: cannot import name 'OrderPayment'
```

Would you need more information about our setup to track this down?

Thank you.

**Comment by thegcat** [comment] 2018-09-07 10:01
Ah, nevermind, I just read that 1.x should be used for Pretix 1.

Isn't there any provisions in the Pretix plugin API to make sure only compatible plugins are installed/loaded? If not I would like to propose this as an enhancement to Pretix :-)

**Comment by thegcat** [comment] 2018-09-07 10:07
For anyone stumbling upon this and as python-unsavvy as I am: It seems pip supports passing version requirements in the installation statement. The following should make sure you don't install version 2.0 yet but still get the newest version available:

```
pip3 install "pretix-cashpayment<2.0"
```

(don't forget to activate your venv before executing the above command)

**Comment by pc-coholic** [comment] 2018-10-01 10:59
Hello!

Sorry for the long delay in answering you - vacation time and such...

Unfortunately, this is indeed working "as intended" - even if the result is not a good one.

As of now, there seems to be no way to properly handle the 1.x/2.x problem except by installing the plugin like you proposed.

For now, I'll close this issue and add the pip-command proposed by you to the readme - hopefully, this will help others. If there is any new development that makes handling different base-versions easier, I'll be happy to implement it.

**Closed as completed by pc-coholic** 2018-10-01 10:59 UTC
